name: Build and push packages to PackageCloud.

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-24.04

    container:
      image: debian:testing
      env:
        DEBIAN_FRONTEND: noninteractive

    steps:
      - uses: actions/checkout@v4

      - name: Install necessary packages
        run: apt -q update && apt -yy install devscripts equivs lintian ruby-full sudo

      - name: Install PackageCloud
        run: gem install package_cloud

      - name: Generate Debian package
        run: |
          sudo ./gh-build.sh

      - name: Push package.
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: |
          package_cloud push nitrux/testing/debian/forky $(pwd)/*.deb
